GET http://localhost:3000/posts/

###

GET http://localhost:3000/posts/63a9509afff3f745534d01a2/

###

GET http://localhost:3000/posts/63a9509afff3f745534d01a2/comments/

###

POST http://localhost:3000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E5YmFiNDY0N2Q5NDY5ODk4NTFiNzkiLCJpYXQiOjE2NzIxMjcwMDYyNjQsImV4cCI6MTY3MjEyNzA5MjY2NH0.j7NR-JuaA72NE_21d9PEosmztIaPfXPa1N8nHe2O5Xk

{
  "title": "A new testing post",
  "text": "NEW test 3",
  "author": "63a9509afff3f745534d019b"
}

###

POST http://localhost:3000/posts/63a9509afff3f745534d01a2/comments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E5YmFiNDY0N2Q5NDY5ODk4NTFiNzkiLCJpYXQiOjE2NzIxMjcwMDYyNjQsImV4cCI6MTY3MjEyNzA5MjY2NH0.j7NR-JuaA72NE_21d9PEosmztIaPfXPa1N8nHe2O5Xk

{
  "text": "Great test comment4"
}

###

POST http://localhost:3000/users/register/
Content-Type: application/json

{
  "username": "6example",
  "email": "6example@example.com",
  "password": "123"
}

###

POST http://localhost:3000/users/login/
Content-Type: application/json

{
  "username": "5example",
  "password": "123"
}

###

GET http://localhost:3000/users/protected/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E5YmE4MWUzYWM1ZTdhMDY0ODI2YTciLCJpYXQiOjE2NzIxNDAxMDEwODYsImV4cCI6MTY3MjE0MDE4NzQ4Nn0.SytzbyVEHV0FHT_JH0ZOFxQwVcsUgqj_oxMIJVM8VII